import { createElement } from '@lwc/engine-dom';
import Scenerio01_ButtonClickEvent from 'c/scenerio01_ButtonClickEvent';

describe('c-scenerio01-button-click-event', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-scenerio01-button-click-event', {
            is: Scenerio01_ButtonClickEvent
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});